FROM node:24-alpine
# RUN apt update \
#     && apt upgrade -y
# #    && apt install -y build-essential libssl-dev libgdbm-dev libdb-dev libexpat-dev libncurses5-dev libbz2-dev zlib1g-dev gawk bison
# RUN apt install wget -y
# RUN wget https://mirror.yandex.ru/debian/pool/main/g/glibc/glibc-source_2.42-11_all.deb
# RUN dpkg -i glibc-source_2.42-11_all.deb
# RUN apt-get update
# RUN export LD_LIBRARY_PATH=/usr/local/glibc-2.42/lib:$LD_LIBRARY_PATH
RUN npm install -g npm@11.16.0
